import type { QuestionCategory } from "./constants";

export type DeckCard = { category: QuestionCategory; prompt: string };

export const DECK: DeckCard[] = [
  { category: "playful", prompt: "What is a tiny thing that always makes your day better?" },
  { category: "hypothetical", prompt: "If we could teleport anywhere tonight, where are we going?" },
  { category: "funny", prompt: "What is an oddly specific thing you love?" },
  { category: "nostalgic", prompt: "What is a smell that takes you straight back to being small?" },
  { category: "deep", prompt: "When did you last feel proud of yourself, even quietly?" },
  { category: "romantic", prompt: "What is a moment with me you still think about?" },
  { category: "random", prompt: "What song have you had on repeat, and why that one?" },
  { category: "playful", prompt: "If we opened a tiny shop, what would we sell?" },
  { category: "hypothetical", prompt: "We have one hour and no phones. How do we spend it?" },
  { category: "deep", prompt: "What do you wish people asked you more often?" },
  { category: "nostalgic", prompt: "What is a place that still feels like yours?" },
  { category: "romantic", prompt: "What is something I do that you hope I never stop?" },
  { category: "random", prompt: "What food are you currently obsessed with?" },
  { category: "funny", prompt: "Which animal are we, as a pair?" },
  { category: "hypothetical", prompt: "If we swapped lives for a day, what should I not mess up?" },
  { category: "deep", prompt: "What have you been carrying that you haven't said out loud?" },
  { category: "nostalgic", prompt: "What is an inside joke you never want us to forget?" },
  { category: "romantic", prompt: "When do you feel closest to me, even if we are apart?" },
  { category: "funny", prompt: "What is the most useless talent you have?" },
  { category: "playful", prompt: "What would our theme song be this week?" },
  { category: "hypothetical", prompt: "If we could invite one fictional character to dinner, who sits with us?" },
  { category: "deep", prompt: "What does a good day look like for you, specifically?" },
  { category: "nostalgic", prompt: "What is a photo you wish we had taken?" },
  { category: "romantic", prompt: "What is a small way you like to be cared for?" },
  { category: "random", prompt: "What is something you believe that is slightly ridiculous?" },
  { category: "playful", prompt: "Rainy Sunday. What are we doing?" },
  { category: "hypothetical", prompt: "We can only keep three objects from your place. Which ones?" },
  { category: "deep", prompt: "What are you looking forward to that has nothing to do with being productive?" },
  { category: "nostalgic", prompt: "What is the first thing you remember about us?" },
  { category: "romantic", prompt: "What nickname should exist for us that doesn't yet?" },
  { category: "funny", prompt: "What is a hill you are weirdly willing to die on?" },
  { category: "playful", prompt: "If our space had a soundtrack right now, what just started playing?" },
  { category: "deep", prompt: "What do you need less of this week?" },
  { category: "romantic", prompt: "What is a future ordinary day with me that you like imagining?" },
  { category: "random", prompt: "What is a tiny luxury you refuse to feel guilty about?" },
  { category: "funny", prompt: "What would the title of our sitcom be?" },
];
